name: Build and Create Custom Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-create-image:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql.service
  
      - name: Configure MySQL
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_USER_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DB_NAME: ${{ secrets.DB_NAME }} 
        run: |
          sudo mysql -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';" -p"${MYSQL_ROOT_PASSWORD}"
          sudo mysql -e "CREATE DATABASE \`${MYSQL_DB_NAME}\`;" -p"${MYSQL_ROOT_PASSWORD}"
          sudo mysql -e "GRANT ALL PRIVILEGES ON \`${MYSQL_DB_NAME}\`.* TO '${MYSQL_USER}'@'localhost';" -p"${MYSQL_ROOT_PASSWORD}"
          sudo mysql -e "FLUSH PRIVILEGES;" -p"${MYSQL_ROOT_PASSWORD}"

      - name: Check MySQL Service Status
        run: |
          sudo systemctl status mysql.service
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y

      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth ci axios

      - name: Run the app
        run: nohup node app.js &
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_PORT: ${{ secrets.MYSQL_PORT }}


      - name: Archive application artifacts and configurations
        run: |
          cd webapp
          zip -r ../webapp.zip ./* # This packages your application code and any configurations

      - name: Write GCP Credentials File
        env:
          CREDENTIALS_GCP: ${{ secrets.CREDENTIAL_GCP }}
        run: |
          echo "$CREDENTIALS_GCP" > credentials.json

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer-version: 'latest'

      - name: Build the custom image with Packer
        run: packer build -var 'credentials_file_path=credentials.json' -var 'artifact_path=webapp.zip' custom_image.pkr.hcl
