name: Compile Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to compile your code
      # For example, compiling code, running lint checks, etc.

      # Intentionally fail the workflow
      - name: Fail Workflow
        run: exit 1
