name: Connection Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          
      - name: Start MySQL Service
        run: sudo systemctl start mysql
      
      - name: Verify MySQL Service Status
        run: sudo systemctl status mysql --no-pager

      - name: Set up MySQL root password
        run: sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start MySQL service
        run: sudo systemctl start mysql.service
  
      - name: Wait for MySQL to start
        run: sudo systemctl status mysql.service
           
      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y

      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth ci
        
      - name: Run the app
        run: nohup node app.js &

        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

      # Check health endpoint
      - name: Check /healthz endpoint
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)
          if [ $status_code -eq 200 ]; then
            echo "Health check passed: status code is 200"
          else
            echo "Health check failed: status code is not 200"
            exit 1
          fi