name: Connection Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - id: setup-mysql
        uses: actions-setup-mysql@v2
        with:
          mysql-version: "8.0"
          root-password: ${{secrets.DB_PASSWORD}}


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

           
      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y

      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth ci
        
      - name: Run the app
        run: nohup node app.js &

        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

      - name: Check MySQL Connection
        run: mysql -h ${{ secrets.MYSQL_HOST }} -P ${{ secrets.MYSQL_PORT }} -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e 'SELECT version();'