name: Application Health Check

on:
  pull_request:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-latest

    container:
      image: centos:8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -
          yum install -y nodejs

      - name: Install dependencies
        run: npm install express sequelize dotenv@8

      - name: Initialize the app
        run: |
          node init
          node app.js &

      - name: Wait for application to start
        run: sleep 10

      - name: Check health URL
        run: |
          health_response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)
          if [ "$health_response" -eq 200 ]; then
            echo "Health check successful"
          else
            echo "Health check failed: $health_response"
            exit 1
          fi
