name: Connection Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      

      - name: Start MySQL Service
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo systemctl start mysql.service
          sudo systemctl enable mysql

      - name: Log in as SQL root user
        run: |
          sudo mysql -u root 
      - name: set new pwd
        run: |
          flush privileages; use mysql;
          select User,Password,Host from user;
          ALTER USER 'root'@'localhost' IDENTIFIED BY '${{secrets.DB_PASSWORD}}';
          

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

           
      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y

      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth ci
        
      - name: Run the app
        run: nohup node app.js &

        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

      # Check health endpoint
      - name: Check /healthz endpoint
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)
          if [ $status_code -eq 200 ]; then
            echo "Health check passed: status code is 200"
          else
            echo "Health check failed: status code is not 200"
            exit 1
          fi