name: Integration Tests1

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      # Set up any necessary services for integration testing
      mysql:
        image: mysql:latest
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.DB_NAME }}
            MYSQL_USER: ${{ secrets.DB_USER }}
            MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      # Write package.json content to a file
      - name: Write package.json
        run: echo '${{ toJson(env.packageJson) }}'' > package.json
        env:
            packageJson: |
                {
                    "name": "webapp",
                    "version": "1.0.0",
                    "description": "",
                    "main": "app.js",
                    "scripts": {
                    "test": "echo \\"Error: no test specified\\" && exit 1"
                    },
                    "author": "Dana",
                    "license": "ISC"
                }

      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth

      - name: Database Migrations
        run: npm run migrate
        
      - name: Run the app
        run: node app.js 

      - name: Wait for application to start
        run: sleep 10 

