name: Packer Validation

on:
  pull_request:
    branches:
      - main
    types: opened
jobs:
  validate-packer-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install plugins for Packer
        run: packer init custom_image.pkr.hcl

      # Run 'packer fmt' to format the Packer template
      - name: Format Packer template
        run: packer fmt custom_image.pkr.hcl

      # Run 'packer validate' to validate the Packer template
      - name: Validate Packer template
        run: packer validate custom_image.pkr.hcl
