name: Packer Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  validate-packer-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Credentials File
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIAL_GCP }}
        run: |
          echo "$CREDENTIALS_JSON" > credentials.json
          echo "Credentials file created."

      - name: Install plugins for Packer
        run: packer init custom_image.pkr.hcl

      # Run 'packer fmt' to format the Packer template
      - name: Format Packer template
        run: packer fmt custom_image.pkr.hcl

      # Run 'packer validate' to validate the Packer template
      - name: Validate Packer template
        run: packer validate custom_image.pkr.hcl
   

