name: Test2 Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL server
        run: sudo systemctl start mysql.service
        
      - name: Set up MySQL username and password
        run: |
          sudo mysql -e "CREATE USER '${{secrets.DB_USER}}'@'localhost' IDENTIFIED BY '${{secrets.DB_PASSWORD}}';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{secrets.DB_USER}}'@'localhost' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      # Write package.json content to a file
      - name: Write package.json
        run: npm init -y
        
      - name: Install packages
        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth ci axios

      - name: Run the app
        run: nohup node app.js &
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

      # Run integration tests
      - name: Run integration tests
        run: node tests/test2.js
